export interface Vecindad {
    value: number;
    label: string;
    depto: number;
  }
  
  export const vecindad: Vecindad[] = [
  
    { value: 101, label: "Guatemala, Guatemala", depto: 1 },
    { value: 101, label: "Guatemala, Guatemala", depto: 1  },
    { value: 102, label: "Santa Catarina Pinula, Guatemala", depto: 1  },
    { value: 103, label: "San José Pinula, Guatemala", depto: 1  },
    { value: 104, label: "San José del Golfo, Guatemala", depto: 1  },
    { value: 105, label: "Palencia, Guatemala", depto: 1  },
    { value: 106, label: "Chinautla, Guatemala", depto: 1  },
    { value: 107, label: "San Pedro Ayampuc, Guatemala", depto: 1  },
    { value: 108, label: "Mixco, Guatemala", depto: 1  },
    { value: 109, label: "San Pedro Sacatepéquez, Guatemala", depto: 1  },
    { value: 110, label: "San Juan Sacatepéquez, Guatemala", depto: 1  },
    { value: 111, label: "San Raymundo, Guatemala", depto: 1  },
    { value: 112, label: "Chuarrancho, Guatemala", depto: 1  },
    { value: 113, label: "Fraijanes, Guatemala", depto: 1  },
    { value: 114, label: "Amatitlán, Guatemala", depto: 1  },
    { value: 115, label: "Villa Nueva, Guatemala", depto: 1  },
    { value: 116, label: "Villa Canales, Guatemala", depto: 1  },
    { value: 117, label: "San Miguel Petapa, Guatemala", depto: 1  },
    { value: 201, label: "Guastatoya, El Progreso", depto: 2  },
    { value: 202, label: "Morazán, El Progreso", depto: 2 },
    { value: 203, label: "San Agustín Acasaguastlán, El Progreso", depto: 2  },
    { value: 204, label: "San Cristóbal Acasaguastlán, El Progreso", depto: 2 },
    { value: 205, label: "El Jícaro, El Progreso", depto: 2 },
    { value: 206, label: "Sansare, El Progreso", depto: 2 },
    { value: 207, label: "Sanarate, El Progreso", depto: 2 },
    { value: 208, label: "San Antonio La Paz, El Progreso", depto: 2 },
    { value: 301, label: "Antigua Guatemala, Sacatepéquez", depto: 3 },
    { value: 302, label: "Jocotenango, Sacatepéquez", depto: 3 },
    { value: 303, label: "Pastores, Sacatepéquez", depto: 3 },
    { value: 304, label: "Sumpango, Sacatepéquez", depto: 3 },
    { value: 305, label: "Santo Domingo Xenacoj, Sacatepéquez", depto: 3 },
    { value: 306, label: "Santiago Sacatepéquez, Sacatepéquez", depto: 3 },
    { value: 307, label: "San Bartolomé Milpas Altas, Sacatepéquez", depto: 3 },
    { value: 308, label: "San Lucas Sacatepéquez, Sacatepéquez", depto: 3 },
    { value: 309, label: "Santa Lucía Milpas Altas, Sacatepéquez", depto: 3 },
    { value: 310, label: "Magdalena Milpas Altas, Sacatepéquez", depto: 3 },
    { value: 311, label: "Santa María de Jesús, Sacatepéquez", depto: 3 },
    { value: 312, label: "Ciudad Vieja, Sacatepéquez", depto: 3 },
    { value: 313, label: "San Miguel Dueñas, Sacatepéquez", depto: 3 },
    { value: 314, label: "San Juan Alotenango, Sacatepéquez", depto: 3 },
    { value: 315, label: "San Antonio Aguas Calientes, Sacatepéquez", depto: 3 },
    { value: 316, label: "Santa Catarina Barahona, Sacatepéquez", depto: 3 },
    { value: 401, label: "Chimaltenango, Chimaltenango", depto: 4 },
    { value: 402, label: "San José Poaquil, Chimaltenango", depto: 4 },
    { value: 403, label: "San Martín Jilotepeque, Chimaltenango", depto: 4 },
    { value: 404, label: "San Juan Comalapa, Chimaltenango", depto: 4 },
    { value: 405, label: "Santa Apolonia, Chimaltenango", depto: 4 },
    { value: 406, label: "Tecpán Guatemala, Chimaltenango", depto: 4 },
    { value: 407, label: "Patzún, Chimaltenango", depto: 4 },
    { value: 408, label: "San Miguel Pochuta, Chimaltenango", depto: 4 },
    { value: 409, label: "Patzicía, Chimaltenango", depto: 4 },
    { value: 410, label: "Santa Cruz Balanyá, Chimaltenango", depto: 4 },
    { value: 411, label: "Acatenango, Chimaltenango", depto: 4 },
    { value: 412, label: "San Pedro Yepocapa, Chimaltenango", depto: 4 },
    { value: 413, label: "San Andrés Itzapa, Chimaltenango", depto: 4 },
    { value: 414, label: "Parramos, Chimaltenango", depto: 4 },
    { value: 415, label: "Zaragoza, Chimaltenango", depto: 4 },
    { value: 416, label: "El Tejar, Chimaltenango", depto: 4 },
    { value: 501, label: "Escuintla, Escuintla", depto: 5 },
    { value: 502, label: "Santa Lucía Cotzumalguapa, Escuintla", depto: 5 },
    { value: 503, label: "La Democracia, Escuintla", depto: 5 },
    { value: 504, label: "Siquinalá, Escuintla", depto: 5 },
    { value: 505, label: "Masagua, Escuintla", depto: 5 },
    { value: 506, label: "Tiquisate, Escuintla", depto: 5 },
    { value: 507, label: "La Gomera, Escuintla", depto: 5 },
    { value: 508, label: "Guanagazapa, Escuintla", depto: 5 },
    { value: 509, label: "San José, Escuintla", depto: 5 },
    { value: 510, label: "Iztapa, Escuintla", depto: 5 },
    { value: 511, label: "Palín, Escuintla", depto: 5 },
    { value: 512, label: "San Vicente Pacaya, Escuintla", depto: 5 },
    { value: 513, label: "Nueva Concepción, Escuintla", depto: 5 },
    { value: 514, label: "Sipacate, Escuintla", depto: 5 },
    { value: 601, label: "Cuilapa, Santa Rosa", depto: 6 },
    { value: 602, label: "Barberena, Santa Rosa", depto: 6 },
    { value: 603, label: "Santa Rosa de Lima, Santa Rosa", depto: 6 },
    { value: 604, label: "Casillas, Santa Rosa", depto: 6 },
    { value: 605, label: "San Rafael Las Flores, Santa Rosa", depto: 6 },
    { value: 606, label: "Oratorio, Santa Rosa", depto: 6 },
    { value: 607, label: "San Juan Tecuaco, Santa Rosa", depto: 6 },
    { value: 608, label: "Chiquimulilla, Santa Rosa", depto: 6 },
    { value: 609, label: "Taxisco, Santa Rosa", depto: 6 },
    { value: 610, label: "Santa María Ixhuatán, Santa Rosa", depto: 6 },
    { value: 611, label: "Guazacapán, Santa Rosa", depto: 6 },
    { value: 612, label: "Santa Cruz Naranjo, Santa Rosa", depto: 6 },
    { value: 613, label: "Pueblo Nuevo Viñas, Santa Rosa", depto: 6 },
    { value: 701, label: "Sololá, Sololá", depto: 7 },
    { value: 702, label: "San José Chacayá, Sololá", depto: 7 },
    { value: 703, label: "Santa María Visitación, Sololá", depto: 7 },
    { value: 704, label: "Santa Lucía Utatlán, Sololá", depto: 7 },
    { value: 705, label: "Nahualá, Sololá", depto: 7 },
    { value: 706, label: "Santa Catarina Ixtahuacan, Sololá", depto: 7 },
    { value: 707, label: "Santa Clara La Laguna, Sololá", depto: 7 },
    { value: 708, label: "Concepción, Sololá", depto: 7 },
    { value: 709, label: "San Andrés Semetabaj, Sololá", depto: 7 },
    { value: 710, label: "Panajachel, Sololá", depto: 7 },
    { value: 711, label: "Santa Catarina Palopó, Sololá", depto: 7 },
    { value: 712, label: "San Antonio Palopó, Sololá", depto: 7 },
    { value: 713, label: "San Lucas Tolimán, Sololá", depto: 7 },
    { value: 714, label: "Santa Cruz La Laguna, Sololá", depto: 7 },
    { value: 715, label: "San Pablo La Laguna, Sololá", depto: 7 },
    { value: 716, label: "San Marcos La Laguna, Sololá", depto: 7 },
    { value: 717, label: "San Juan La Laguna, Sololá", depto: 7 },
    { value: 718, label: "San Pedro La Laguna, Sololá", depto: 7 },
    { value: 719, label: "Santiago Atitlán, Sololá", depto: 7 },
    { value: 801, label: "Totonicapán, Totonicapán", depto: 8 },
    { value: 802, label: "San Cristóbal Totonicapán, Totonicapán", depto: 8 },
    { value: 803, label: "San Francisco El Alto, Totonicapán", depto: 8 },
    { value: 804, label: "San Andrés Xecul, Totonicapán", depto: 8 },
    { value: 805, label: "Momostenango, Totonicapán", depto: 8 },
    { value: 806, label: "Santa María Chiquimula, Totonicapán", depto: 8 },
    { value: 807, label: "Santa Lucía la Reforma, Totonicapán", depto: 8 },
    { value: 808, label: "San Bartolo Aguas Calientes, Totonicapán", depto: 8 },
    { value: 901, label: "Quetzaltenango, Quetzaltenango", depto: 9 },
    { value: 902, label: "Salcajá, Quetzaltenango", depto: 9 },
    { value: 903, label: "Olintepeque, Quetzaltenango", depto: 9 },
    { value: 904, label: "San Carlos Sija, Quetzaltenango", depto: 9 },
    { value: 905, label: "Sibilia, Quetzaltenango", depto: 9 },
    { value: 906, label: "Cabricán, Quetzaltenango", depto: 9 },
    { value: 907, label: "Cajolá, Quetzaltenango", depto: 9 },
    { value: 908, label: "San Miguel Siguilá, Quetzaltenango", depto: 9 },
    { value: 909, label: "Ostuncalco, Quetzaltenango", depto: 9 },
    { value: 910, label: "San Mateo, Quetzaltenango", depto: 9 },
    { value: 911, label: "Concepción Chiquirichapa, Quetzaltenango", depto: 9 },
    { value: 912, label: "San Martín Sacatepéquez, Quetzaltenango", depto: 9 },
    { value: 913, label: "Almolonga, Quetzaltenango", depto: 9 },
    { value: 914, label: "Cantel, Quetzaltenango", depto: 9 },
    { value: 915, label: "Huitán, Quetzaltenango", depto: 9 },
    { value: 916, label: "Zunil, Quetzaltenango", depto: 9 },
    { value: 917, label: "Colomba, Quetzaltenango", depto: 9 },
    { value: 918, label: "San Francisco La Unión, Quetzaltenango", depto: 9 },
    { value: 919, label: "El Palmar, Quetzaltenango", depto: 9 },
    { value: 920, label: "Coatepeque, Quetzaltenango", depto: 9 },
    { value: 921, label: "Genova, Quetzaltenango", depto: 9 },
    { value: 1001, label: "Mazatenango, Suchitepéquez", depto: 10 },
    { value: 1002, label: "Cuyotenango, Suchitepéquez", depto: 10 },
    { value: 1003, label: "San Francisco Zapotitlán, Suchitepéquez", depto: 10 },
    { value: 1004, label: "San Bernardino, Suchitepéquez", depto: 10 },
    { value: 1005, label: "San José El Ídolo, Suchitepéquez", depto: 10 },
    { value: 1006, label: "Santo Domingo Suchitepéquez, Suchitepéquez", depto: 10 },
    { value: 1007, label: "San Lorenzo, Suchitepéquez", depto: 10 },
    { value: 1008, label: "Samayac, Suchitepéquez", depto: 10 },
    { value: 1009, label: "San Pablo Jocopilas, Suchitepéquez", depto: 10 },
    { value: 1010, label: "San Antonio Suchitepéquez, Suchitepéquez", depto: 10 },
    { value: 1011, label: "San Miguel Panán, Suchitepéquez", depto: 10 },
    { value: 1012, label: "San Gabriel, Suchitepéquez", depto: 10 },
    { value: 1013, label: "Chicacao, Suchitepéquez", depto: 10 },
    { value: 1014, label: "Patulul, Suchitepéquez", depto: 10 },
    { value: 1015, label: "Santa Bárbara, Suchitepéquez", depto: 10 },
    { value: 1016, label: "San Juan Bautista, Suchitepéquez", depto: 10 },
    { value: 1017, label: "Santo Tomás La Unión, Suchitepéquez", depto: 10 },
    { value: 1018, label: "Zunilito, Suchitepéquez", depto: 10 },
    { value: 1019, label: "Pueblo Nuevo, Suchitepéquez", depto: 10 },
    { value: 1101, label: "Retalhuleu, Retalhuleu", depto: 11 },
    { value: 1102, label: "San Sebastián, Retalhuleu", depto: 11 },
    { value: 1103, label: "Santa Cruz Muluá, Retalhuleu", depto: 11 },
    { value: 1104, label: "San Martín Zapotitlán, Retalhuleu", depto: 11 },
    { value: 1105, label: "San Felipe, Retalhuleu", depto: 11 },
    { value: 1106, label: "San Andrés Villa Seca, Retalhuleu", depto: 11 },
    { value: 1107, label: "Champerico, Retalhuleu", depto: 11 },
    { value: 1108, label: "Nuevo San Carlos, Retalhuleu", depto: 11 },
    { value: 1201, label: "San Marcos, San Marcos", depto: 12 },
    { value: 1202, label: "San Pedro Sacatepéquez, San Marcos", depto: 12 },
    { value: 1203, label: "San Antonio Sacatepéquez, San Marcos", depto: 12 },
    { value: 1204, label: "Comitancillo, San Marcos", depto: 12 },
    { value: 1205, label: "San Miguel Ixtahuacán, San Marcos", depto: 12 },
    { value: 1206, label: "Concepción Tutuapa, San Marcos", depto: 12 },
    { value: 1207, label: "Tacaná, San Marcos", depto: 12 },
    { value: 1208, label: "Sibinal, San Marcos", depto: 12 },
    { value: 1209, label: "Tajumulco, San Marcos", depto: 12 },
    { value: 1210, label: "Tejutla, San Marcos", depto: 12 },
    { value: 1211, label: "San Rafael Pie de la Cuesta, San Marcos", depto: 12 },
    { value: 1212, label: "Nuevo Progreso, San Marcos", depto: 12 },
    { value: 1213, label: "El Tumbador, San Marcos", depto: 12 },
    { value: 1214, label: "El Rodeo, San Marcos", depto: 12 },
    { value: 1215, label: "Malacatán, San Marcos", depto: 12 },
    { value: 1216, label: "Catarina, San Marcos", depto: 12 },
    { value: 1217, label: "Ayutla, San Marcos", depto: 12 },
    { value: 1218, label: "Ocos, San Marcos", depto: 12 },
    { value: 1219, label: "San Pablo, San Marcos", depto: 12 },
    { value: 1220, label: "El Quetzal, San Marcos", depto: 12 },
    { value: 1221, label: "La Reforma, San Marcos", depto: 12 },
    { value: 1222, label: "Pajapita, San Marcos", depto: 12 },
    { value: 1223, label: "Ixchiguán, San Marcos", depto: 12 },
    { value: 1301, label: "Huehuetenango, Huehuetenango", depto: 13 },
    { value: 1302, label: "Chiantla, Huehuetenango", depto: 13 },
    { value: 1303, label: "Malacatancito, Huehuetenango", depto: 13 },
    { value: 1304, label: "Cuilco, Huehuetenango", depto: 13 },
    { value: 1305, label: "Nentón, Huehuetenango", depto: 13 },
    { value: 1306, label: "San Pedro Necta, Huehuetenango", depto: 13 },
    { value: 1307, label: "Jacaltenango, Huehuetenango", depto: 13 },
    { value: 1308, label: "Soloma, Huehuetenango", depto: 13 },
    { value: 1309, label: "Ixtahuacán, Huehuetenango", depto: 13 },
    { value: 1310, label: "Santa Bárbara, Huehuetenango", depto: 13 },
    { value: 1311, label: "La Libertad, Huehuetenango", depto: 13 },
    { value: 1312, label: "La Democracia, Huehuetenango", depto: 13 },
    { value: 1313, label: "San Miguel Acatán, Huehuetenango", depto: 13 },
    { value: 1314, label: "San Rafael La Independencia, Huehuetenango", depto: 13 },
    { value: 1315, label: "Todos Santos Cuchumatán, Huehuetenango", depto: 13 },
    { value: 1316, label: "San Juan Atitán, Huehuetenango", depto: 13 },
    { value: 1317, label: "Santa Eulalia, Huehuetenango", depto: 13 },
    { value: 1318, label: "San Mateo Ixtatán, Huehuetenango", depto: 13 },
    { value: 1319, label: "Colotenango, Huehuetenango", depto: 13 },
    { value: 1320, label: "San Sebastián Coatán, Huehuetenango", depto: 13 },
    { value: 1321, label: "Concepción Huista, Huehuetenango", depto: 13 },
    { value: 1322, label: "San Juan Ixcoy, Huehuetenango", depto: 13 },
    { value: 1323, label: "San Antonio Huista, Huehuetenango", depto: 13 },
    { value: 1324, label: "San Sebastián Huehuetenango, Huehuetenango", depto: 13 },
    { value: 1325, label: "Santa Cruz Barillas, Huehuetenango", depto: 13 },
    { value: 1326, label: "San Gaspar Ixchil, Huehuetenango", depto: 13 },
    { value: 1327, label: "Aguacatán, Huehuetenango", depto: 13 },
    { value: 1328, label: "San Rafael Pétzal, Huehuetenango", depto: 13 },
    { value: 1329, label: "San Gaspar Ixchil, Huehuetenango", depto: 13 },
    { value: 1330, label: "Santiago Chimaltenango, Huehuetenango", depto: 13 },
    { value: 1331, label: "Santa Ana Huista, Huehuetenango", depto: 13 },
    { value: 1401, label: "Santa Cruz del Quiché, Quiché", depto: 14 },
    { value: 1402, label: "Chiché, Quiché", depto: 14 },
    { value: 1403, label: "Chinique, Quiché", depto: 14 },
    { value: 1404, label: "Zacualpa, Quiché", depto: 14 },
    { value: 1405, label: "Chajul, Quiché", depto: 14 },
    { value: 1406, label: "Chichicastenango, Quiché", depto: 14 },
    { value: 1407, label: "Patzité, Quiché", depto: 14 },
    { value: 1408, label: "San Antonio Ilotenango, Quiché", depto: 14 },
    { value: 1409, label: "San Pedro Jocopilas, Quiché", depto: 14 },
    { value: 1410, label: "Cunén, Quiché", depto: 14 },
    { value: 1411, label: "San Juan Cotzal, Quiché", depto: 14 },
    { value: 1412, label: "Joyabaj, Quiché", depto: 14 },
    { value: 1413, label: "Santa María Nebaj, Quiché", depto: 14 },
    { value: 1414, label: "San Andrés Sajcabajá, Quiché", depto: 14 },
    { value: 1415, label: "San Miguel Uspantán, Quiché", depto: 14 },
    { value: 1416, label: "Sacapulas, Quiché", depto: 14 },
    { value: 1417, label: "San Bartolomé Jocotenango, Quiché", depto: 14 },
    { value: 1418, label: "Canillá, Quiché", depto: 14 },
    { value: 1419, label: "Chicamán, Quiché", depto: 14 },
    { value: 1420, label: "Playa Grande Ixcán, Quiché", depto: 14 },
    { value: 1421, label: "Pachalum, Quiché", depto: 14 },
    { value: 1501, label: "Salamá, Baja Verapaz", depto: 15 },
    { value: 1502, label: "San Miguel Chicaj, Baja Verapaz", depto: 15 },
    { value: 1503, label: "Rabinal, Baja Verapaz", depto: 15 },
    { value: 1504, label: "Cubulco, Baja Verapaz", depto: 15 },
    { value: 1505, label: "Granados, Baja Verapaz", depto: 15 },
    { value: 1506, label: 'Santa Cruz El Chol, Baja Verapaz', depto: 15 },
    { value: 1507, label: 'San Jerónimo, Baja Verapaz', depto: 15 },
    { value: 1508, label: 'Purulhá, Baja Verapaz', depto: 15 },
    { value: 1601, label: 'Cobán, Alta Verapaz', depto: 16 },
    { value: 1602, label: 'Santa Cruz Verapaz, Alta Verapaz', depto: 16 },
    { value: 1603, label: 'San Cristóbal Verapaz, Alta Verapaz', depto: 16 },
    { value: 1604, label: 'Tactic, Alta Verapaz', depto: 16 },
    { value: 1605, label: 'Tamahú, Alta Verapaz', depto: 16 },
    { value: 1606, label: 'San Miguel Tucurú, Alta Verapaz', depto: 16 },
    { value: 1607, label: 'Panzós, Alta Verapaz', depto: 16 },
    { value: 1608, label: 'Senahú, Alta Verapaz', depto: 16 },
    { value: 1609, label: 'San Pedro Carchá, Alta Verapaz', depto: 16 },
    { value: 1610, label: 'San Juan Chamelco, Alta Verapaz', depto: 16 },
    { value: 1611, label: 'San Agustín Lanquín, Alta Verapaz', depto: 16 },
    { value: 1612, label: 'Santa María Cahabón, Alta Verapaz', depto: 16 },
    { value: 1613, label: 'Chisec, Alta Verapaz', depto: 16 },
    { value: 1614, label: 'Chahal, Alta Verapaz', depto: 16 },
    { value: 1615, label: 'Fray Bartolomé de Las Casas, Alta Verapaz', depto: 16 },
    { value: 1616, label: 'Santa Catalina La Tinta, Alta Verapaz', depto: 16 },
    { value: 1617, label: 'Raxruhá, Alta Verapaz', depto: 16 },
    { value: 1701, label: 'Flores, Petén', depto: 17 },
    { value: 1702, label: 'San José, Petén', depto: 17 },
    { value: 1703, label: 'San Benito, Petén', depto: 17 },
    { value: 1704, label: 'San Andrés, Petén', depto: 17 },
    { value: 1705, label: 'La Libertad, Petén', depto: 17 },
    { value: 1706, label: 'San Francisco, Petén', depto: 17 },
    { value: 1707, label: 'Santa Ana, Petén', depto: 17 },
    { value: 1708, label: 'Dolores, Petén', depto: 17 },
    { value: 1709, label: 'San Luis, Petén', depto: 17 },
    { value: 1710, label: 'Sayaxché, Petén', depto: 17 },
    { value: 1711, label: 'Melchor de Mencos, Petén', depto: 17 },
    { value: 1712, label: 'Poptún, Petén', depto: 17 },
    { value: 1713, label: 'Las Cruces, Petén', depto: 17 },
    { value: 1714, label: 'El Chal, Petén', depto: 17 },
    { value: 1801, label: 'Puerto Barrios, Izabal', depto: 18 },
    { value: 1802, label: 'Livingston, Izabal', depto: 18 },
    { value: 1803, label: 'El Estor, Izabal', depto: 18 },
    { value: 1804, label: 'Morales, Izabal', depto: 18 },
    { value: 1805, label: 'Los Amates, Izabal', depto: 18 },
    { value: 1901, label: 'Zacapa, Zacapa', depto: 19 },
    { value: 1902, label: 'Estanzuela, Zacapa', depto: 19 },
    { value: 1903, label: 'Río Hondo, Zacapa', depto: 19 },
    { value: 1904, label: 'Gualán, Zacapa', depto: 19 },
    { value: 1905, label: 'Teculután, Zacapa', depto: 19 },
    { value: 1906, label: 'Usumatlán, Zacapa', depto: 19 },
    { value: 1907, label: 'Cabañas, Zacapa', depto: 19 },
    { value: 1908, label: 'San Diego, Zacapa', depto: 19 },
    { value: 1909, label: 'La Unión, Zacapa', depto: 19 },
    { value: 1910, label: 'Huité, Zacapa', depto: 19 },
    { value: 1911, label: 'San Jorge, Zacapa', depto: 19 },
    { value: 2001, label: 'Chiquimula, Chiquimula', depto: 20 },
    { value: 2002, label: 'San José La Arada, Chiquimula', depto: 20 },
    { value: 2003, label: 'San Juan Ermita' , depto: 20 },
    { value: 2004, label: 'Jocotán Chiquimula, Chiquimula', depto: 20 },
    { value: 2005, label: 'Camotán Chiquimula, Chiquimula', depto: 20 },
    { value: 2006, label: 'Olopa Chiquimula, Chiquimula', depto: 20 },
    { value: 2007, label: 'Esquipulas, Chiquimula', depto: 20 },
    { value: 2008, label: 'Concepción Las Minas Chiquimula, Chiquimula', depto: 20 },
    { value: 2009, label: 'Quezaltepeque Chiquimula, Chiquimula', depto: 20 },
    { value: 2010, label: 'San Jacinto Chiquimula, Chiquimula', depto: 20 },
    { value: 2011, label: 'Ipala Chiquimula, Chiquimula', depto: 20 },
    { value: 2101, label: 'Jalapa, Jalapa', depto: 21 },
    { value: 2102, label: 'San Pedro Pinula, Jalapa', depto: 21 },
    { value: 2103, label: 'San Luis Jilotepeque, Jalapa', depto: 21 },
    { value: 2104, label: 'San Manuel Chaparrón, Jalapa', depto: 21 },
    { value: 2105, label: 'San Carlos Alzatate, Jalapa', depto: 21 },
    { value: 2106, label: 'Monjas, Jalapa', depto: 21 },
    { value: 2107, label: 'Mataquescuintla, Jalapa', depto: 21 },
    { value: 2201, label: 'Jutiapa, Jutiapa', depto: 22 },
    { value: 2202, label: 'El Progreso, Jutiapa', depto: 22 },
    { value: 2203, label: 'Santa Catarina Mita, Jutiapa', depto: 22 },
    { value: 2204, label: 'Agua Blanca, Jutiapa', depto: 22 },
    { value: 2205, label: 'Asunción Mita, Jutiapa', depto: 22 },
    { value: 2206, label: 'Yupiltepeque, Jutiapa', depto: 22 },
    { value: 2207, label: 'Atescatempa, Jutiapa', depto: 22 },
    { value: 2208, label: 'Jerez, Jutiapa', depto: 22 },
    { value: 2209, label: 'El Adelanto, Jutiapa', depto: 22 },
    { value: 2210, label: 'Zapotitlán, Jutiapa', depto: 22 },
    { value: 2211, label: 'Comapa, Jutiapa', depto: 22 },
    { value: 2212, label: 'Jalpatagua, Jutiapa', depto: 22 },
    { value: 2213, label: 'Conguaco, Jutiapa', depto: 22 },
    { value: 2214, label: 'Moyuta, Jutiapa', depto: 22 },
    { value: 2215, label: 'Pasaco, Jutiapa', depto: 22 },
    { value: 2216, label: 'San José Acatempa, Jutiapa', depto: 22 },
    { value: 2217, label: 'Quesada, Jutiapa', depto: 22 }
  ]
  
  export interface Departamentos {
    value: number;
    label: string;
  }
  
  export const departamentos: Departamentos[] = [
    { value: 1, label: 'Guatemala' },
    { value: 2, label: 'El Progreso' },
    { value: 3, label: 'Sacatepéquez' },
    { value: 4, label: 'Chimaltenango' },
    { value: 5, label: 'Escuintla' },
    { value: 6, label: 'Santa Rosa' },
    { value: 7, label: 'Sololá' },
    { value: 8, label: 'Totonicapán' },
    { value: 9, label: 'Quetzaltenango' },
    { value: 10, label: 'Suchitepéquez' },
    { value: 11, label: 'Retalhuleu' },
    { value: 12, label: 'San Marcos' },
    { value: 13, label: 'Huehuetenango' },
    { value: 14, label: 'Quiché' },
    { value: 15, label: 'Baja Verapaz' },
    { value: 16, label: 'Alta Verapaz' },
    { value: 17, label: 'Petén' },
    { value: 18, label: 'Izabal' },
    { value: 19, label: 'Zacapa' },
    { value: 20, label: 'Chiquimula' },
    { value: 21, label: 'Jalapa' },
    { value: 22, label: 'Jutiapa' },
    { value: 99, label: 'Otro Pais'}
  
  ]
  
  export interface Municipio {
    value: number;
    label: string;
    depto: number;
  }
  
  export const municipio: Municipio[] = [
  
    { value: 101, label: "Guatemala", depto: 1 },
    { value: 101, label: "Guatemala", depto: 1  },
    { value: 102, label: "Santa Catarina Pinula", depto: 1  },
    { value: 103, label: "San José Pinula", depto: 1  },
    { value: 104, label: "San José del Golfo", depto: 1  },
    { value: 105, label: "Palencia", depto: 1  },
    { value: 106, label: "Chinautla", depto: 1  },
    { value: 107, label: "San Pedro Ayampuc", depto: 1  },
    { value: 108, label: "Mixco", depto: 1  },
    { value: 109, label: "San Pedro Sacatepéquez", depto: 1  },
    { value: 110, label: "San Juan Sacatepéquez", depto: 1  },
    { value: 111, label: "San Raymundo", depto: 1  },
    { value: 112, label: "Chuarrancho", depto: 1  },
    { value: 113, label: "Fraijanes", depto: 1  },
    { value: 114, label: "Amatitlán", depto: 1  },
    { value: 115, label: "Villa Nueva", depto: 1  },
    { value: 116, label: "Villa Canales", depto: 1  },
    { value: 117, label: "San Miguel Petapa", depto: 1  },
    { value: 201, label: "Guastatoya", depto: 2  },
    { value: 202, label: "Morazán", depto: 2 },
    { value: 203, label: "San Agustín Acasaguastlán", depto: 2  },
    { value: 204, label: "San Cristóbal Acasaguastlán", depto: 2 },
    { value: 205, label: "El Jícaro", depto: 2 },
    { value: 206, label: "Sansare", depto: 2 },
    { value: 207, label: "Sanarate", depto: 2 },
    { value: 208, label: "San Antonio La Paz", depto: 2 },
    { value: 301, label: "Antigua Guatemala", depto: 3 },
    { value: 302, label: "Jocotenango", depto: 3 },
    { value: 303, label: "Pastores", depto: 3 },
    { value: 304, label: "Sumpango", depto: 3 },
    { value: 305, label: "Santo Domingo Xenacoj", depto: 3 },
    { value: 306, label: "Santiago Sacatepéquez", depto: 3 },
    { value: 307, label: "San Bartolomé Milpas Altas", depto: 3 },
    { value: 308, label: "San Lucas Sacatepéquez", depto: 3 },
    { value: 309, label: "Santa Lucía Milpas Altas", depto: 3 },
    { value: 310, label: "Magdalena Milpas Altas", depto: 3 },
    { value: 311, label: "Santa María de Jesús", depto: 3 },
    { value: 312, label: "Ciudad Vieja", depto: 3 },
    { value: 313, label: "San Miguel Dueñas", depto: 3 },
    { value: 314, label: "San Juan Alotenango", depto: 3 },
    { value: 315, label: "San Antonio Aguas Calientes", depto: 3 },
    { value: 316, label: "Santa Catarina Barahona", depto: 3 },
    { value: 401, label: "Chimaltenango", depto: 4 },
    { value: 402, label: "San José Poaquil", depto: 4 },
    { value: 403, label: "San Martín Jilotepeque", depto: 4 },
    { value: 404, label: "San Juan Comalapa", depto: 4 },
    { value: 405, label: "Santa Apolonia", depto: 4 },
    { value: 406, label: "Tecpán Guatemala", depto: 4 },
    { value: 407, label: "Patzún", depto: 4 },
    { value: 408, label: "San Miguel Pochuta", depto: 4 },
    { value: 409, label: "Patzicía", depto: 4 },
    { value: 410, label: "Santa Cruz Balanyá", depto: 4 },
    { value: 411, label: "Acatenango", depto: 4 },
    { value: 412, label: "San Pedro Yepocapa", depto: 4 },
    { value: 413, label: "San Andrés Itzapa", depto: 4 },
    { value: 414, label: "Parramos", depto: 4 },
    { value: 415, label: "Zaragoza", depto: 4 },
    { value: 416, label: "El Tejar", depto: 4 },
    { value: 501, label: "Escuintla", depto: 5 },
    { value: 502, label: "Santa Lucía Cotzumalguapa", depto: 5 },
    { value: 503, label: "La Democracia", depto: 5 },
    { value: 504, label: "Siquinalá", depto: 5 },
    { value: 505, label: "Masagua", depto: 5 },
    { value: 506, label: "Tiquisate", depto: 5 },
    { value: 507, label: "La Gomera", depto: 5 },
    { value: 508, label: "Guanagazapa", depto: 5 },
    { value: 509, label: "San José", depto: 5 },
    { value: 510, label: "Iztapa", depto: 5 },
    { value: 511, label: "Palín", depto: 5 },
    { value: 512, label: "San Vicente Pacaya", depto: 5 },
    { value: 513, label: "Nueva Concepción", depto: 5 },
    { value: 514, label: "Sipacate", depto: 5 },
    { value: 601, label: "Cuilapa", depto: 6 },
    { value: 602, label: "Barberena", depto: 6 },
    { value: 603, label: "Santa Rosa de Lima", depto: 6 },
    { value: 604, label: "Casillas", depto: 6 },
    { value: 605, label: "San Rafael Las Flores", depto: 6 },
    { value: 606, label: "Oratorio", depto: 6 },
    { value: 607, label: "San Juan Tecuaco", depto: 6 },
    { value: 608, label: "Chiquimulilla", depto: 6 },
    { value: 609, label: "Taxisco", depto: 6 },
    { value: 610, label: "Santa María Ixhuatán", depto: 6 },
    { value: 611, label: "Guazacapán", depto: 6 },
    { value: 612, label: "Santa Cruz Naranjo", depto: 6 },
    { value: 613, label: "Pueblo Nuevo Viñas", depto: 6 },
    { value: 701, label: "Sololá", depto: 7 },
    { value: 702, label: "San José Chacayá", depto: 7 },
    { value: 703, label: "Santa María Visitación", depto: 7 },
    { value: 704, label: "Santa Lucía Utatlán", depto: 7 },
    { value: 705, label: "Nahualá", depto: 7 },
    { value: 706, label: "Santa Catarina Ixtahuacan", depto: 7 },
    { value: 707, label: "Santa Clara La Laguna", depto: 7 },
    { value: 708, label: "Concepción", depto: 7 },
    { value: 709, label: "San Andrés Semetabaj", depto: 7 },
    { value: 710, label: "Panajachel", depto: 7 },
    { value: 711, label: "Santa Catarina Palopó", depto: 7 },
    { value: 712, label: "San Antonio Palopó", depto: 7 },
    { value: 713, label: "San Lucas Tolimán", depto: 7 },
    { value: 714, label: "Santa Cruz La Laguna", depto: 7 },
    { value: 715, label: "San Pablo La Laguna", depto: 7 },
    { value: 716, label: "San Marcos La Laguna", depto: 7 },
    { value: 717, label: "San Juan La Laguna", depto: 7 },
    { value: 718, label: "San Pedro La Laguna", depto: 7 },
    { value: 719, label: "Santiago Atitlán", depto: 7 },
    { value: 801, label: "Totonicapán", depto: 8 },
    { value: 802, label: "San Cristóbal Totonicapán", depto: 8 },
    { value: 803, label: "San Francisco El Alto", depto: 8 },
    { value: 804, label: "San Andrés Xecul", depto: 8 },
    { value: 805, label: "Momostenango", depto: 8 },
    { value: 806, label: "Santa María Chiquimula", depto: 8 },
    { value: 807, label: "Santa Lucía La Reforma", depto: 8 },
    { value: 808, label: "San Bartolo Aguas Calientes", depto: 8 },
    { value: 901, label: "Quetzaltenango", depto: 9 },
    { value: 902, label: "Salcajá", depto: 9 },
    { value: 903, label: "Olintepeque", depto: 9 },
    { value: 904, label: "San Carlos Sija", depto: 9 },
    { value: 905, label: "Sibilia", depto: 9 },
    { value: 906, label: "Cabricán", depto: 9 },
    { value: 907, label: "Cajolá", depto: 9 },
    { value: 908, label: "San Miguel Siguilá", depto: 9 },
    { value: 909, label: "Ostuncalco", depto: 9 },
    { value: 910, label: "San Mateo", depto: 9 },
    { value: 911, label: "Concepción Chiquirichapa", depto: 9 },
    { value: 912, label: "San Martín Sacatepéquez", depto: 9 },
    { value: 913, label: "Almolonga", depto: 9 },
    { value: 914, label: "Cantel", depto: 9 },
    { value: 915, label: "Huitán", depto: 9 },
    { value: 916, label: "Zunil", depto: 9 },
    { value: 917, label: "Colomba", depto: 9 },
    { value: 918, label: "San Francisco La Unión", depto: 9 },
    { value: 919, label: "El Palmar", depto: 9 },
    { value: 920, label: "Coatepeque", depto: 9 },
    { value: 921, label: "Genova", depto: 9 },
    { value: 1001, label: "Mazatenango", depto: 10 },
    { value: 1002, label: "Cuyotenango", depto: 10 },
    { value: 1003, label: "San Francisco Zapotitlán", depto: 10 },
    { value: 1004, label: "San Bernardino", depto: 10 },
    { value: 1005, label: "San José El Ídolo", depto: 10 },
    { value: 1006, label: "Santo Domingo Suchitepéquez", depto: 10 },
    { value: 1007, label: "San Lorenzo", depto: 10 },
    { value: 1008, label: "Samayac", depto: 10 },
    { value: 1009, label: "San Pablo Jocopilas", depto: 10 },
    { value: 1010, label: "San Antonio Suchitepéquez", depto: 10 },
    { value: 1011, label: "San Miguel Panán", depto: 10 },
    { value: 1012, label: "San Gabriel", depto: 10 },
    { value: 1013, label: "Chicacao", depto: 10 },
    { value: 1014, label: "Patulul", depto: 10 },
    { value: 1015, label: "Santa Bárbara", depto: 10 },
    { value: 1016, label: "San Juan Bautista", depto: 10 },
    { value: 1017, label: "Santo Tomás La Unión", depto: 10 },
    { value: 1018, label: "Zunilito", depto: 10 },
    { value: 1019, label: "Pueblo Nuevo", depto: 10 },
    { value: 1101, label: "Retalhuleu", depto: 11 },
    { value: 1102, label: "San Sebastián", depto: 11 },
    { value: 1103, label: "Santa Cruz Muluá", depto: 11 },
    { value: 1104, label: "San Martín Zapotitlán", depto: 11 },
    { value: 1105, label: "San Felipe", depto: 11 },
    { value: 1106, label: "San Andrés Villa Seca", depto: 11 },
    { value: 1107, label: "Champerico", depto: 11 },
    { value: 1108, label: "Nuevo San Carlos", depto: 11 },
    { value: 1201, label: "San Marcos", depto: 12 },
    { value: 1202, label: "San Pedro Sacatepéquez", depto: 12 },
    { value: 1203, label: "San Antonio Sacatepéquez", depto: 12 },
    { value: 1204, label: "Comitancillo", depto: 12 },
    { value: 1205, label: "San Miguel Ixtahuacán", depto: 12 },
    { value: 1206, label: "Concepción Tutuapa", depto: 12 },
    { value: 1207, label: "Tacaná", depto: 12 },
    { value: 1208, label: "Sibinal", depto: 12 },
    { value: 1209, label: "Tajumulco", depto: 12 },
    { value: 1210, label: "Tejutla", depto: 12 },
    { value: 1211, label: "San Rafael Pie de la Cuesta", depto: 12 },
    { value: 1212, label: "Nuevo Progreso", depto: 12 },
    { value: 1213, label: "El Tumbador", depto: 12 },
    { value: 1214, label: "El Rodeo", depto: 12 },
    { value: 1215, label: "Malacatán", depto: 12 },
    { value: 1216, label: "Catarina", depto: 12 },
    { value: 1217, label: "Ayutla", depto: 12 },
    { value: 1218, label: "Ocos", depto: 12 },
    { value: 1219, label: "San Pablo", depto: 12 },
    { value: 1220, label: "El Quetzal", depto: 12 },
    { value: 1221, label: "La Reforma", depto: 12 },
    { value: 1222, label: "Pajapita", depto: 12 },
    { value: 1223, label: "Ixchiguán", depto: 12 },
    { value: 1301, label: "Huehuetenango", depto: 13 },
    { value: 1302, label: "Chiantla", depto: 13 },
    { value: 1303, label: "Malacatancito", depto: 13 },
    { value: 1304, label: "Cuilco", depto: 13 },
    { value: 1305, label: "Nentón", depto: 13 },
    { value: 1306, label: "San Pedro Necta", depto: 13 },
    { value: 1307, label: "Jacaltenango", depto: 13 },
    { value: 1308, label: "Soloma", depto: 13 },
    { value: 1309, label: "Ixtahuacán", depto: 13 },
    { value: 1310, label: "Santa Bárbara", depto: 13 },
    { value: 1311, label: "La Libertad", depto: 13 },
    { value: 1312, label: "La Democracia", depto: 13 },
    { value: 1313, label: "San Miguel Acatán", depto: 13 },
    { value: 1314, label: "San Rafael La Independencia", depto: 13 },
    { value: 1315, label: "Todos Santos Cuchumatán", depto: 13 },
    { value: 1316, label: "San Juan Atitán", depto: 13 },
    { value: 1317, label: "Santa Eulalia", depto: 13 },
    { value: 1318, label: "San Mateo Ixtatán", depto: 13 },
    { value: 1319, label: "Colotenango", depto: 13 },
    { value: 1320, label: "San Sebastián Coatán", depto: 13 },
    { value: 1321, label: "Concepción Huista", depto: 13 },
    { value: 1322, label: "San Juan Ixcoy", depto: 13 },
    { value: 1323, label: "San Antonio Huista", depto: 13 },
    { value: 1324, label: "San Sebastián Huehuetenango", depto: 13 },
    { value: 1325, label: "Santa Cruz Barillas", depto: 13 },
    { value: 1326, label: "San Gaspar Ixchil", depto: 13 },
    { value: 1327, label: "Aguacatán", depto: 13 },
    { value: 1328, label: "San Rafael Pétzal", depto: 13 },
    { value: 1329, label: "San Gaspar Ixchil", depto: 13 },
    { value: 1330, label: "Santiago Chimaltenango", depto: 13 },
    { value: 1331, label: "Santa Ana Huista", depto: 13 },
    { value: 1401, label: "Santa Cruz del Quiché", depto: 14 },
    { value: 1402, label: "Chiché", depto: 14 },
    { value: 1403, label: "Chinique", depto: 14 },
    { value: 1404, label: "Zacualpa", depto: 14 },
    { value: 1405, label: "Chajul", depto: 14 },
    { value: 1406, label: "Chichicastenango", depto: 14 },
    { value: 1407, label: "Patzité", depto: 14 },
    { value: 1408, label: "San Antonio Ilotenango", depto: 14 },
    { value: 1409, label: "San Pedro Jocopilas", depto: 14 },
    { value: 1410, label: "Cunén", depto: 14 },
    { value: 1411, label: "San Juan Cotzal", depto: 14 },
    { value: 1412, label: "Joyabaj", depto: 14 },
    { value: 1413, label: "Santa María Nebaj", depto: 14 },
    { value: 1414, label: "San Andrés Sajcabajá", depto: 14 },
    { value: 1415, label: "San Miguel Uspantán", depto: 14 },
    { value: 1416, label: "Sacapulas", depto: 14 },
    { value: 1417, label: "San Bartolomé Jocotenango", depto: 14 },
    { value: 1418, label: "Canillá", depto: 14 },
    { value: 1419, label: "Chicamán", depto: 14 },
    { value: 1420, label: "Playa Grande Ixcán", depto: 14 },
    { value: 1421, label: "Pachalum", depto: 14 },
    { value: 1501, label: "Salamá", depto: 15 },
    { value: 1502, label: "San Miguel Chicaj", depto: 15 },
    { value: 1503, label: "Rabinal", depto: 15 },
    { value: 1504, label: "Cubulco", depto: 15 },
    { value: 1505, label: "Granados", depto: 15 },
    { value: 1506, label: 'Santa Cruz El Chol', depto: 15 },
    { value: 1507, label: 'San Jerónimo', depto: 15 },
    { value: 1508, label: 'Purulhá', depto: 15 },
    { value: 1601, label: 'Cobán', depto: 16 },
    { value: 1602, label: 'Santa Cruz Verapaz', depto: 16 },
    { value: 1603, label: 'San Cristóbal Verapaz', depto: 16 },
    { value: 1604, label: 'Tactic', depto: 16 },
    { value: 1605, label: 'Tamahú', depto: 16 },
    { value: 1606, label: 'San Miguel Tucurú', depto: 16 },
    { value: 1607, label: 'Panzós', depto: 16 },
    { value: 1608, label: 'Senahú', depto: 16 },
    { value: 1609, label: 'San Pedro Carchá', depto: 16 },
    { value: 1610, label: 'San Juan Chamelco', depto: 16 },
    { value: 1611, label: 'San Agustín Lanquín', depto: 16 },
    { value: 1612, label: 'Santa María Cahabón', depto: 16 },
    { value: 1613, label: 'Chisec', depto: 16 },
    { value: 1614, label: 'Chahal', depto: 16 },
    { value: 1615, label: 'Fray Bartolomé de Las Casas', depto: 16 },
    { value: 1616, label: 'Santa Catalina La Tinta', depto: 16 },
    { value: 1617, label: 'Raxruhá', depto: 16 },
    { value: 1701, label: 'Flores', depto: 17 },
    { value: 1702, label: 'San José', depto: 17 },
    { value: 1703, label: 'San Benito', depto: 17 },
    { value: 1704, label: 'San Andrés', depto: 17 },
    { value: 1705, label: 'La Libertad', depto: 17 },
    { value: 1706, label: 'San Francisco', depto: 17 },
    { value: 1707, label: 'Santa Ana', depto: 17 },
    { value: 1708, label: 'Dolores', depto: 17 },
    { value: 1709, label: 'San Luis', depto: 17 },
    { value: 1710, label: 'Sayaxché', depto: 17 },
    { value: 1711, label: 'Melchor de Mencos', depto: 17 },
    { value: 1712, label: 'Poptún', depto: 17 },
    { value: 1713, label: 'Las Cruces', depto: 17 },
    { value: 1714, label: 'El Chal', depto: 17 },
    { value: 1801, label: 'Puerto Barrios', depto: 18 },
    { value: 1802, label: 'Livingston', depto: 18 },
    { value: 1803, label: 'El Estor', depto: 18 },
    { value: 1804, label: 'Morales', depto: 18 },
    { value: 1805, label: 'Los Amates', depto: 18 },
    { value: 1901, label: 'Zacapa', depto: 19 },
    { value: 1902, label: 'Estanzuela', depto: 19 },
    { value: 1903, label: 'Río Hondo', depto: 19 },
    { value: 1904, label: 'Gualán', depto: 19 },
    { value: 1905, label: 'Teculután', depto: 19 },
    { value: 1906, label: 'Usumatlán', depto: 19 },
    { value: 1907, label: 'Cabañas', depto: 19 },
    { value: 1908, label: 'San Diego', depto: 19 },
    { value: 1909, label: 'La Unión', depto: 19 },
    { value: 1910, label: 'Huité', depto: 19 },
    { value: 1911, label: 'San Jorge', depto: 19 },
    { value: 2001, label: 'Chiquimula', depto: 20 },
    { value: 2002, label: 'San José La Arada', depto: 20 },
    { value: 2003, label: 'San Juan Ermita' , depto: 20 },
    { value: 2004, label: 'Jocotán Chiquimula', depto: 20 },
    { value: 2005, label: 'Camotán Chiquimula', depto: 20 },
    { value: 2006, label: 'Olopa Chiquimula', depto: 20 },
    { value: 2007, label: 'Esquipulas', depto: 20 },
    { value: 2008, label: 'Concepción Las Minas Chiquimula', depto: 20 },
    { value: 2009, label: 'Quezaltepeque Chiquimula', depto: 20 },
    { value: 2010, label: 'San Jacinto Chiquimula', depto: 20 },
    { value: 2011, label: 'Ipala Chiquimula', depto: 20 },
    { value: 2101, label: 'Jalapa', depto: 21 },
    { value: 2102, label: 'San Pedro Pinula', depto: 21 },
    { value: 2103, label: 'San Luis Jilotepeque', depto: 21 },
    { value: 2104, label: 'San Manuel Chaparrón', depto: 21 },
    { value: 2105, label: 'San Carlos Alzatate', depto: 21 },
    { value: 2106, label: 'Monjas', depto: 21 },
    { value: 2107, label: 'Mataquescuintla', depto: 21 },
    { value: 2201, label: 'Jutiapa', depto: 22 },
    { value: 2202, label: 'El Progreso', depto: 22 },
    { value: 2203, label: 'Santa Catarina Mita', depto: 22 },
    { value: 2204, label: 'Agua Blanca', depto: 22 },
    { value: 2205, label: 'Asunción Mita', depto: 22 },
    { value: 2206, label: 'Yupiltepeque', depto: 22 },
    { value: 2207, label: 'Atescatempa', depto: 22 },
    { value: 2208, label: 'Jerez', depto: 22 },
    { value: 2209, label: 'El Adelanto', depto: 22 },
    { value: 2210, label: 'Zapotitlán', depto: 22 },
    { value: 2211, label: 'Comapa', depto: 22 },
    { value: 2212, label: 'Jalpatagua', depto: 22 },
    { value: 2213, label: 'Conguaco', depto: 22 },
    { value: 2214, label: 'Moyuta', depto: 22 },
    { value: 2215, label: 'Pasaco', depto: 22 },
    { value: 2216, label: 'San José Acatempa', depto: 22 },
    { value: 2217, label: 'Quesada', depto: 22 },
    { value: 9, label: 'Otro Pais', depto: 99}
  ]
  